import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:share_plus/share_plus.dart';
import '../core/theme/colors.dart';
import '../core/theme/typography.dart';
import '../widgets/custom_button.dart';
import '../widgets/before_after_view.dart';
import '../providers/instruction_provider.dart';
import '../models/final_output.dart';
import 'input_screen.dart';

class OutputScreen extends ConsumerStatefulWidget {
  const OutputScreen({super.key});

  @override
  ConsumerState<OutputScreen> createState() => _OutputScreenState();
}

class _OutputScreenState extends ConsumerState<OutputScreen> {
  FinalOutput? _output;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _generateFinalInstruction();
  }

  Future<void> _generateFinalInstruction() async {
    final instruction = ref.read(currentInstructionProvider);
    final clarifications = ref.read(selectedClarificationsProvider);

    if (instruction == null) return;

    setState(() => _isLoading = true);

    try {
      final output = await ref.read(
        generateFinalInstructionProvider((
          instruction: instruction.originalText,
          clarifications: clarifications,
        )).future,
      );

      ref.read(finalOutputProvider.notifier).state = output;

      setState(() {
        _output = output;
        _isLoading = false;
      });
    } catch (e) {
      setState(() => _isLoading = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error generating final instruction: $e')),
        );
      }
    }
  }

  void _copyToClipboard() {
    if (_output == null) return;

    Clipboard.setData(ClipboardData(text: _output!.clarified));

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text('Copied to clipboard!'),
        backgroundColor: AppColors.success,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
      ),
    );
  }

  void _shareInstruction(BuildContext context) {
    if (_output == null) return;

    final RenderBox? box = context.findRenderObject() as RenderBox?;
    if (box == null) return;

    Share.share(
      'Clarified Instruction:\n\n${_output!.clarified}\n\n---\nGenerated by Instruction Clarifier AI',
      subject: 'Clarified Instruction',
      sharePositionOrigin: box.localToGlobal(Offset.zero) & box.size,
    );
  }

  void _startNew() {
    // Clear all state
    ref.read(currentInstructionProvider.notifier).state = null;
    ref.read(ambiguityAnalysisProvider.notifier).state = null;
    ref.read(clarificationQuestionProvider.notifier).state = null;
    ref.read(selectedClarificationsProvider.notifier).state = {};
    ref.read(finalOutputProvider.notifier).state = null;

    // Navigate to input screen
    Navigator.pushAndRemoveUntil(
      context,
      MaterialPageRoute(builder: (context) => const InputScreen()),
      (route) => false,
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    if (_isLoading) {
      return Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const CircularProgressIndicator(),
              const SizedBox(height: 24),
              Text(
                'Generating your clarified instruction...',
                style: AppTypography.bodyLarge,
              ),
            ],
          ),
        ),
      );
    }

    if (_output == null) {
      return const Scaffold(
        body: Center(
          child: Text('No output available'),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Image.asset('assets/images/logo_horizontal.png', height: 32),
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: const SizedBox(), // Remove back button
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Success header
              Container(
                padding: const EdgeInsets.all(20),
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: [
                      AppColors.success.withOpacity(0.1),
                      AppColors.primary.withOpacity(0.1),
                    ],
                  ),
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    color: AppColors.success.withOpacity(0.3),
                  ),
                ),
                child: Row(
                  children: [
                    Icon(
                      Icons.check_circle,
                      color: AppColors.success,
                      size: 32,
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Instruction Clarified!',
                            style: AppTypography.h3.copyWith(
                              color: AppColors.success,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'Your instruction is now clear and AI-ready',
                            style: AppTypography.bodySmall.copyWith(
                              color: isDark
                                  ? AppColors.textDarkSecondary
                                  : AppColors.textLightSecondary,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ).animate().fadeIn(delay: 100.ms).scale(),

              const SizedBox(height: 32),

              // Before/After comparison
              BeforeAfterView(output: _output!),

              const SizedBox(height: 32),

              // Structured instruction
              Container(
                padding: const EdgeInsets.all(20),
                decoration: BoxDecoration(
                  color: isDark ? AppColors.darkCard : AppColors.lightCard,
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'STRUCTURED BREAKDOWN',
                      style: AppTypography.overline.copyWith(
                        color: AppColors.primary,
                      ),
                    ),
                    const SizedBox(height: 16),
                    _buildStructuredItem('Goal', _output!.structured.goal),
                    _buildStructuredItem('Style', _output!.structured.style),
                    _buildStructuredItem(
                      'Constraints',
                      _output!.structured.constraints.join('\n• '),
                      isList: true,
                    ),
                    _buildStructuredItem(
                      'Expected Outcome',
                      _output!.structured.expectedOutcome,
                    ),
                  ],
                ),
              ).animate().fadeIn(delay: 800.ms),

              const SizedBox(height: 24),

              // Hint text
              Center(
                child: Text(
                  '✨ Use this instruction with any AI tool',
                  textAlign: TextAlign.center,
                  style: AppTypography.caption.copyWith(
                    color: (isDark
                            ? AppColors.textDarkSecondary
                            : AppColors.textLightSecondary)
                        .withOpacity(0.6),
                    fontStyle: FontStyle.italic,
                  ),
                ),
              ).animate().fadeIn(delay: 1000.ms),

              const SizedBox(height: 24),

              // Action buttons
              Row(
                children: [
                  Expanded(
                    child: CustomButton(
                      text: 'Copy',
                      onPressed: _copyToClipboard,
                      icon: Icons.copy,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: CustomButton(
                      text: 'Share',
                      onPressed: () => _shareInstruction(context),
                      type: ButtonType.secondary,
                      icon: Icons.share,
                    ),
                  ),
                ],
              ).animate().fadeIn(delay: 1200.ms),

              const SizedBox(height: 12),

              CustomButton(
                text: 'Start New',
                onPressed: _startNew,
                type: ButtonType.tertiary,
                icon: Icons.refresh,
              ).animate().fadeIn(delay: 1400.ms),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildStructuredItem(String label, String value, {bool isList = false}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: AppTypography.caption.copyWith(
              color: AppColors.primary,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            isList ? '• $value' : value,
            style: AppTypography.bodyMedium.copyWith(
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}
